# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='itou_c4_python_api',
    version='0.1.0',
    description='Python API for JS Tracker',
    python_requires='<4.0,>=3.8',
    author='pmontens',
    author_email='pieterjan@montens.net',
    entry_points={"console_scripts": ["api = webservice.main:main"]},
    packages=['webservice'],
    package_dir={"": ".", "webservice": "./webservice"},
    package_data={},
    install_requires=[
        'asyncpg==0.*,>=0.21.0', 'fastapi==0.*,>=0.61.1',
        'pytz==2020.*,>=2020.1.0', 'pyyaml==5.*,>=5.3.1',
        'uvicorn==0.*,>=0.11.8'
    ],
    extras_require={
        "dev": [
            "flake8==3.*,>=3.8.3", "isort==5.*,>=5.4.2", "pylint==2.*,>=2.6.0"
        ]
    },
)
